### PR TITLE
Adjust some styling of the newsletter components

### PR DESCRIPTION
**Pull request by weilbith**
Closes: trustlines-network/project#807

We should wait for [this story](https://github.com/trustlines-network/project/issues/808) so that @andfletcher can actually review the changes to avoid mistakes like for the preceding PR.

### CODE REVIEW

**Comment by weilbith** [comment]
CI must fail for the moment, since PR #39 is not merged yet. I can rebase this branch as soon as it has been integrated to `master`.

**Comment by schmir-at-bb** [comment]
I've rebased that. @andfletcher You can take a look at the preview here:

https://preview.trustlines.foundation.test.beercoin.io

**Comment by andfletcher** [comment]
Looks good to go! Tatu also look over it and its good to go.

**Comment by weilbith** [comment]
Awesome. :hugs: 
@schmir-at-bb or @berndbohmeier could you please merge this PR? Thanks!

**Pull request merged**
